### ISSUE TITLE
最新的latest运行报错

### ISSUE THREAD

**Issue by wxnode** [mogeko/docker-vlmcsd#45]
我的compose配置是这样的
```
  vlmcsd:
    container_name: vlmcsd
    image: ghcr.io/mogeko/vlmcsd:latest
    restart: unless-stopped
    ports:
      - 1688:1688
```
运行后一直在重启，然后看了下日志发现报如下错误

```/usr/bin/vlmcsd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/vlmcsd)```
